### ISSUE TITLE
fix the class problem in grafana docs monitoring

### ISSUE THREAD

**Issue by vladimirhasko** [opentelekomcloud-infra/grafana-docs-monitoring#74]
![image](https://github.com/user-attachments/assets/3b51aaa6-cdb9-4a32-8dd3-a4455e9ba1fd)

![image](https://github.com/user-attachments/assets/0b11e291-cbe6-4a9b-9975-5d0851d5f9c3)

**Comment by YustinaKvr** [comment]
This error occurs since GITHUB_FALLBACK_TOKEN is missing in vault.
Currently we need to wait for colleague who is able to add this token to the vault.

**Comment by YustinaKvr** [comment]
Fallback token has been added, script works fine
